In [77]:
import pandas as pd
import numpy as np


In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [17]:
#Question 1. Pandas version
pd.__version__

'2.3.1'

In [18]:
#Question 2. How many records are in the dataset?
num_rows = len(df)
num_rows

9704

In [19]:
#Question 3. How many fuel types are presented in the dataset?
df.fuel_type.nunique()

2

In [21]:
#Question 4. How many columns in the dataset have missing values?
df.isnull().any().sum()

np.int64(4)

In [29]:
#Question 5. What's the maximum fuel efficiency of cars from Asia?
df[(df['origin'].str.lower() == 'asia')].fuel_efficiency_mpg.max()
    

np.float64(23.759122836520497)

In [54]:
#Q6. Median value of horsepower
median = df['horsepower'].median()
median

np.float64(149.0)

In [55]:
mode = df.horsepower.mode()
mode

0    152.0
Name: horsepower, dtype: float64

In [56]:
df['horsepower'] = df['horsepower'].fillna(mode)

In [57]:
median = df['horsepower'].median()
median

np.float64(149.0)

In [72]:
#Q7. Sum of weights
asia_cars = df[(df['origin'].str.lower() == 'asia')]
X = asia_cars[['vehicle_weight', 'model_year']].head(7).values

In [73]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [74]:
XT = X.T

In [75]:
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [78]:
#Vector-vector multiplication
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [79]:
#Matrix-vector multiplication
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [80]:
#Matrix-matrix multiplication
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [90]:
XTX = matrix_matrix_multiplication (XT,X)
XTX

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

In [91]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [92]:
invX = np.linalg.inv(XTX)
invX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [93]:
invX.shape

(2, 2)

In [94]:
XT.shape

(2, 7)

In [95]:
res = matrix_matrix_multiplication (invX,XT)
res

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [96]:
res.shape

(2, 7)

In [97]:
y.shape

(7,)

In [98]:
w = matrix_vector_multiplication(res, y)
w

array([0.01386421, 0.5049067 ])

In [99]:
w.sum()

np.float64(0.5187709081074002)