In [2]:
import numpy as np

In [3]:
np


<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [10]:
a = np.array([1,4,7,8,9])
a

array([1, 4, 7, 8, 9])

In [12]:
a[2]

np.int64(7)

In [13]:
a[2] = 10

In [14]:
a

array([ 1,  4, 10,  8,  9])

In [15]:
range_array = np.arange(10)

In [16]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
linspace_array = np.linspace(0, 1, 11)

In [18]:
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [19]:
zeros_matrix = np.zeros((5, 2))
ones_matrix = np.ones((5, 2))
constant_matrix = np.full((5, 2), 3)

In [20]:
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
#Numpy can create arrays filled with random numbers. To ensure reproducibility, you can set a seed using np.random.seed()
np.random.seed(2)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1

In [24]:
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [25]:
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))

In [26]:
normal_distribution

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [27]:
random_integers

array([[83, 31],
       [66, 80],
       [52, 76],
       [50,  4],
       [90, 63]])

In [28]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[:, 0]  # Gets the first column

In [29]:
arr = arr + 1   # Adds 1 to each element
arr = arr * 2   # Multiplies each element by 2
# Similar operations for division and exponentiation

In [30]:
arr


array([[ 6,  8, 10],
       [10, 12, 14]])

In [31]:
arr1 = np.ones(4)
arr1

array([1., 1., 1., 1.])

In [32]:
arr2 = np.full(4, 3)
arr2

array([3, 3, 3, 3])

In [33]:
result = arr1 + arr2  # Element-wise addition
result = arr1 / arr2  # Element-wise division

In [34]:
result

array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

In [35]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]

In [36]:
greater_than_2

array([False, False,  True,  True])

In [37]:
selected_elements = arr[arr > 1]  # Gets elements greater than 1

In [38]:
selected_elements

array([2, 3, 4])

In [39]:
min_value = arr.min()    # Minimum value
max_value = arr.max()    # Maximum value
sum_value = arr.sum()    # Sum of all elements
mean_value = arr.mean()  # Mean (average) value
std_deviation = arr.std()  # Standard deviation